language: java
jdk:
  - openjdk6
  - openjdk7
install: true
branches:
  only:
    - master
env:
  global:
    secure: "ZZkXt/g2XBCFv4OHXFoohGxJWgSOYWmpLazgOagtGORaOjiou7Lpi2WHMIEOynAVlBOT8/rL+Q3vNeBIzR5CzU9PWqwDGduAKml3CKHGI/hch+vQTX9SQIqRx5KsIpHZzOwx5bG1Zwg+b4pMU1ilOgZwGXJycp975IMBRDQegYWDLoqdXcBOwLfGs8YSUwwNb1wfNZCr+E85mIHPxjnoxYfOb+igUu7Q6C4FoMdzMGSYv6n7SJwXFKK6pz06pY6/wWHboCLnHdopXMVokNUUiYXiEHhHAlOHitirPhBcLnKRPovYmr09siySkMBweEUc4cF9YRt5wEBseGn0Vvof7DOutFzjSIAlhCfJP14NaBGBs7kdAm8OktuPFDDWG/7VfhyCKdNYxauYkSF4x6pB2owI7dxmn7bcX6dzqJG/3lxw6BSoUQ+SH3+EIqhMISHAv7oaEAVFMqBK2uY/cRLUuk/M5cyKoKHE/KY5v5V2CJIgWWn4brEbqEV7a+VAvxxOXdne/iYs4RwJaJL3BUub22ucrwRes0vtF3aqHo1ty8kJhSFm709fkweOAmxtmI4Cqi3fYbC8H+0dtQwkuYuAGoj2e0PqvWIkYj8KwYxnktFqMrBjIXPYWOE27sxXOthFKlzlPbV+cz6/IF/H71HZJIDbxm8inD7HnMYAJcMGZnk="
before_script:
  - echo "before_script start"
  - echo "before_script end"
script:
  - echo "script start"
  - mvn deploy
  - echo "script end"
after_script:
  - echo "after_script start"
  - echo "after_script end"
after_success:
  - echo "after_success"
after_failure:
  - echo "after_failure"

